##### Run configuration #####

run_name: validation_run
input_path: path/to/fastq_pass
output_path: path/to/output

##### Read length filters #####

min_length: 150
max_length: 420

##### Genes amplified #####

genes:
  PRIMA1: PRIMA1
  HSP4: HSP4
  KCNS1: KCNS1
  GM7: GM7

##### Reference panel #####

references_file: references/genes.converted.ambiguous.fasta
substitution_matrix: references/substitution_matrix.txt
cpg_csv: references/cpg_csv.csv

##### Porechop options #####

require_two_barcodes: "True"
discard_middle: "True"
split_reads: "False"
discard_unassigned: "False" #default keep unassigned, change to --discard_unassigned if you don't want to see unbarcoded reads
barcode_set: "native" # [native,rapid,all], defaults to `native`, `all` is much slower
limit_barcodes_to: #barcode csv string e.g. NB01,NB02,NB03,NB04,NB05,NB06
barcode_threshold: 70
barcode_diff: 5

##### Barcodes in run #####

barcodes:
  - NB01
  - NB02
  - NB03
  - NB04
  - NB05
  - NB06
  - NB07
  - NB08
  - NB09
  - NB10
  - NB11
  - NB12
  - NB13
  - NB14
  - NB15
  - NB16
  - NB17
  - NB18
  - NB19
  - NB20
  - NB21
  - NB22
  - NB23
  - NB24